### ISSUE TITLE
FTM isn't holding cached content on app close and relaunch

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#1010]
**Describe the bug**
When loading FTM, closing the app via the Android quick close action (swiping up from the bottom, holding, and releasing), going offline, and launching Curious Reader, it looks like CR thinks it never cached the FTM content so it asks the user to connect to the network to download the files.

**To Reproduce**
1. Download Curious Reader.
2. Open Curious Reader and select a language.
3. Launch FTM and press play.
4. Close the Curious Reader app by swiping up from the bottom.
5. Launch Curious Reader and observe that the 

**Expected behavior**
Closing the Curious Reader app should not clear a sub-apps cache.

**Screenshots**
[Video
](https://drive.google.com/file/d/1hK7XOVRWg1TM-ZeWEPMMy__RWtKGOYpI/view?usp=sharing)

**Smartphone (please complete the following information):**
TBA
 - Device: Samsung Galaxy S22 Ultra
 - OS: Android 14
 - Version: FTM v1.0.26

**Additional context**
N/A

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

There night be a possibility that the issue  might be device specific since we also tried in the same device but with android version 12,
there we were not able to reproduce this issue which points towards possible privacy settings in the device on which we are not able to cache the content using workbox service worker!

Ben,
Will it be possible to have one more short video where we would like to follow these steps:-

1. Clear cache and  storage from setting
2. Then load the content and look for the progress bar whether it is coming or not.

**Comment by burrage** [comment]
Whew this is all good news now that we've tried this on Android 14, 12, and 9 and haven't seen it!

I've passed the clear cache request onward to Jeff so we'll see what comes back! Thanks @amitsinghsutara

**Comment by amitsinghsutara** [comment]
Thanks @burrage🙌

**Comment by burrage** [comment]
Clearing the cache worked to fix this issue. Closing!
