### ISSUE TITLE
Data is sharing between the dev mode and normal mode.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#345]
**Describe the bug**
If we play a random level in dev mode and if we return to normal mode the level data is shared between the 2 modes.

**To Reproduce**
1. Install the dev build from the apk and download the FTM content.
2. Open the CR container app and click on FTM icon.
3. In the play button screen turn on the dev mode by clicking on the dev button at the top, which turns green.
4. Then click on play button and play a level randomly and exit from FTM.
5. Then open FTM in normal mode you can see the data is shared.

**Expected behavior**
Data should not shared between dev and normal mode.

**Screen Record**
https://drive.google.com/file/d/15Pl3suN9r7wHiQO2VkI6dC_nIX_GpwWk/view?usp=share_link

**Smartphone (please complete the following information):**
 - Device: MI Note 6 pro
 - OS: Android 9

**Additional context**

**Comment by burrage** [comment]
@Ashish1998 What data is shared exactly? Say the number of stars someone got on the level?

If so, would this have any effect on your workflow that we couldn't work around (say clearing the cache to wipe out level progress, etc.)?

Just thinking this may be a very low priority issue that can stay in the backlog since this is a feature that will only impact us as the developers and testers.

**Comment by Ashish1998** [comment]
@burrage Data sharing of the stars.
For ex. If we play level 25 in dev mode, and if we open the app in normal mode all the levels till 25 is getting unlocked.
Yean Ben, this issue will only be in dev build.
