### ISSUE TITLE
If we swipe on the screen from right to left, the screen moves.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#358]
**Describe the bug**
If we swipe on the screen from right to left, then the screen moves and we will be able to see a black strip at the right end of the screen.

**To Reproduce**
1. Install the Build with Hindi FTM.
2. Open Hindi FTM and swipe from right to left.
3. The screen moves and a black stripe will be visible.

**Expected behavior**
The screen should not be movable.

**Screen Record **

https://images.zenhubusercontent.com/518897719/f4d1fd9c-c4d3-4b4b-97b1-aa40a5942231/screenrecorder_2023_04_17_12_31_41_891.mp4

**Smartphone (please complete the following information):**
 - Device: MI Note 6 pro
 - OS: Android 9

**Additional context**

**Comment by burrage** [comment]
For context, I'm setting this as a low-priority bug. We should fix it eventually, but I think it would be pretty rare that a user continues to swipe the screen over and over and over, potentially impeding them from selecting an answer or otherwise progressing in the game.

@rakshith-arch This might be an issue that's best to collect more information about using Browser Stack. Are there different devices that have slightly different built-in browsers that will need an edge case that they shouldn't respond to s wipe in this manner?

**Comment by burrage** [comment]
We decided to close this as the issue wasn't happening on all devices and isn't replicable anymore.

So maybe we fixed it by luck...? :-)
