### ISSUE TITLE
Practice release process for FTM Hindi to Prod

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#386]
**User Story**
As a Product Owner,
I want to deploy FTM Hindi to Production,
So that I have a second language available to supplement the release of the language selection feature in production.

**Acceptance Criteria**
Given that I have a release-ready version of Hindi, all the content has been committed to the main branch, and the content has been deployed to the S3 bucket,
When I access the production URL with Hindi as a language,
Then I should be able to play the Hindi version of Feed The Monster in production.

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

 Regarding task for the Hindi production build, it seems that we'll need an updated JSON file. The issue is not just with the prompt audios, but also with some prompt texts and target stones that are missing. As a result, they are currently showing as null values. To ensure a complete and functional Hindi production build, it would be great to have an updated JSON file that includes all the necessary prompt texts and target stones. Thanks!

**Comment by burrage** [comment]
Indeed! We've got 3 dependencies on this task card that must be finished first.

I've re-assigned #372 to you for getting the audio up on the AWS S3 bucket (again, this should be an automated process when committing to GitHub).

#370 and #371-- @weepingwitch will be re-exporting the JSON with the proper URLs and this time around, we'll have the fixes for 'null' or missing items :-) 

Keep an eye on the Slack channel for when these are ready and we can move on this task.
