### ISSUE TITLE
JSON gen process-- detect additional ,s

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#684]
**User Story**
As a developer,
I want to check if a row in the levelgen Google Sheet has exactly 4 commas and throwing an error if there are more than 4 commas or less than 4  commas and to display an error,
So that we can help guide the content lead to input mistakes in the levelgen file.

**Acceptance Criteria**
Given that I have implemented my check of the levelgen file,
When the check occurs,
Then the cell should be highlighted in red if it does not pass the check to alert the pedagogy expert that there are too many, or too little, targets.

**Comment by Nikhil77sutara** [comment]
Hy @burrage 
I wanted to seek some clarification regarding the row validation process we discussed for the levelgen Google Sheet. As you mentioned, the initial requirement was to check if a row has exactly 5 commas and throw an error if there are more or fewer commas, helping guide the content lead to identify input mistakes.
If there are 5 commas within a row, it would indicate the presence of 6 segments or words.
So what if we check for 4 commas because If there are 4 commas within a row, it implies that there are 5 segments or words in that row !

**Comment by Nikhil77sutara** [comment]
And also Ben how to make this changes in the sheet because am not having the access to edit the sheet !

**Comment by burrage** [comment]
Indeed on both fronts, sorry! Permissions updated on the levelgen sheets-- want to give it another go, @Nikhil77sutara ? Thanks!

**Comment by burrage** [comment]
And a note that the solution we came up with SHOULD take care of this and #686 . 

I've updated this specific task card with more details of how we should format a cell on error (e.g. highlight red).
