### ISSUE TITLE
Building and verifying "Arabic"

### ISSUE THREAD

**Issue by divyahariharan2103** [curiouslearning/FeedTheMonsterJS#695]

**Comment by burrage** [comment]
Note from Amit from when we tried Arabic before setting it aside for a while:

"We are also lagging the feedback audio's as well for ftm_arabic!"

**Comment by burrage** [comment]
I know we've put a lot of effort into this language already, and we have been up to a 5 for effort already (!), but I'm curious what the additional would be given where we are now?

Where we are:

- Levelgen completely rebuilt.
- Web content check shows we have all the files.
- Build the app.
- Technical QA check-- spot check: letters show right-to-left and generally look like the same words / characters in the levelgen? Gameplay has letters go from right-to-left?
- If passing technical QA check, we can move it on to the local language expert QA.

**Comment by Ashish1998** [comment]
Issues in the Arabic FTM,

- The feedback audio and the text are in English.
- In one of the word level (level 10) there was 1 answer option missing.

![Screenshot_2024-05-07-11-45-25-49_9654051c21660445b69bc848f64982aa](https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/a9901669-2c61-4f06-b04e-ce1b11b6dca7)

**Comment by burrage** [comment]
@Ashish1998 OK looks like we are going to have to tackle these from a few different fronts...

The feedback text and audio has been sent over to the Content group to fix that.

The incorrect letter options MAY be a font thing that we will have to fix on the technical end. What font are we using for this language?

**Comment by burrage** [comment]
CC: @amitsinghsutara

**Comment by amitsinghsutara** [comment]
hey @burrage ,
We are using Noto-Sans Regular font for this language!

**Comment by burrage** [comment]
@amitsinghsutara Okie dokie... Arabic isn't a supported language for Noto-Sans-- ahhhhhhh!!! So this is making sense...

Do we still have our Adobe Arabic Bold font? Seems like it could be the go-to for this language in particular (it's even got the language name in the font!)

**Comment by amitsinghsutara** [comment]
hey @burrage ,
hope you are doing well ;)

Regarding In one of the word level (level 10) some answer options are missing,
The issue here is that the prompt text is of 10 character length but unfortunately we only have 10 stone positions available in our gameplay due to which we were not able to get all the options!

To tackle this issue Ben we can either add two more positions or from the content end we can have two or three characters in brackets i.e. "[]" which can be helpful in reducing the number of foilstones!

**Comment by burrage** [comment]
Woop! Time out!!! I think you are touching on the crux of the issue here, @amitsinghsutara !

Just to make sure I'm getting this right... let's take this Arabic word from level 10 for example, "حَــسَــمَ".

Does the code in FTM JS say this is 10 characters in length? 

If so, I'll need to revert to Stephanie because, you're right, if we wanted to skip how Arabic combines characters, we would need to start using [ ]s around certain characters. I'm not sure the pedagogy intent here so I'm going to start the convo with Stephanie now regardless.

Thanks for surfacing this!!!

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

Yup that's the case the code in FTM JS say this is 10 characters in length!

**Comment by amitsinghsutara** [comment]
Thanks for understanding 🙌🙌

**Comment by amitsinghsutara** [comment]
Thanks Ben for thoughtful insights 🙌

**Comment by burrage** [comment]
I've confirmed with Stephanie that from the pedagogy perspective, we do NOT want them having to drag 10 stones to make that word. 

So per your recommendation Amit, the Content group will revise the levelgen and figure out what characters they want to put the [ ]s around so we get some combined characters on stones. That way there's less than 10 stones to drag and instead like 2 or 3 depending on what we want to teach. 

So... while that happens, let's go ahead and make the font change. I'm anticipating we'll probably have a few trial and error sessions with the Content group and an Arabic expert since this is combined character stuff is tricky-- especially when we don't know the language! Ahhhhhh!!! 😆

**Comment by amitsinghsutara** [comment]
Yes Ben totally,
As per the font changes we already have an opened pr for that  ;) 
I'll revise that pr having only the font changes!

best Regards
Amit

**Comment by burrage** [comment]
Oh and a heads up, Stephanie also went ahead and made multiple feedback phrases and linked the audio on Drive in the levelgen too.

**Comment by amitsinghsutara** [comment]
hey @burrage ,

Hope you are doing well ;)
Thanks a lot for the updates, we have updated the ftmpwa_arabic build with the levelgen contents!

Best Regards 
Amit

**Comment by burrage** [comment]
Woo!

Keep me posted when we've done a tech QA run and hopefully this is ready to be moved on to the local language expert 😄

**Comment by Ashish1998** [comment]
@burrage Hiii Ben, in Arabic level 10 for one of the word we have same 2 options for a particular letter of a word, here one option is combined and the other is the same letter is split into 2 options.
(you can observe the behavior in the below video)
Please give your feedback on this.


https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/e2632be0-5a33-420d-b0df-6e0dc3f8d68b

**Comment by Ashish1998** [comment]
Other than this we don't have any tech related issues Ben.

**Comment by burrage** [comment]
Awesome @Ashish1998 and @amitsinghsutara ! Yeah I think we're really down to Content QA at this point so I'm going to pass this over to Stephanie and see if she wants to go ahead with the local language expert QA to catch issues like the one in the video.

Thanks guys!

**Comment by burrage** [comment]
Hey question... not sure what's happening here, but I cleared all app data, uninstalled, and I downloaded and installed the latest Dev APK (May 14th) from the development server and I'm not seeing Arabic in my dropdown of languages? Am I missing something? Clearly Ashish has it!!!

**Comment by burrage** [comment]
Can I also confirm that we are using the manifest from the "testing" folder on Dev Wordpress and not the "dev" folder?

**Comment by amitsinghsutara** [comment]
Hey @burrage ,
here's the link to testing apk which Ashish M is using to test the development build changes!
[link](https://github.com/amitsinghsutara/container-app/blob/Amit_1/app-debug.apk)

**Comment by amitsinghsutara** [comment]
Ben regarding the dev folder manifest,
Actually ben we are using that manifest file for the local qa only,
And we are using the testing manifest file to test our latest changes to those languages which are not in local qa!

**Comment by burrage** [comment]
@amitsinghsutara Ah gotcha!

Can we actually update the APK that's in the /APK/ folder on the development S3 bucket please? We have that link hardcoded in a bunch of documentation that Stephanie sends out when we ask the local language experts to QA. Can you also make sure that Arabic is selectable in that dropdown?

I chatted with Stephanie today and she agrees that we should move forward with the language expert QA because we'll be scratching our heads about what's supposed to be combined and what's not otherwise 😂 

Thanks Amit!

**Comment by amitsinghsutara** [comment]
Hey @burrage ,
For sure ;)

Here's the link!
[dev apk](https://feedthemonsterdev.curiouscontent.org/APK/development-curious-reader-QA.apk)
