### ISSUE TITLE
Launch "Thai" language to production

### ISSUE THREAD

**Issue by divyahariharan2103** [curiouslearning/FeedTheMonsterJS#704]
**Acceptance Criteria**
Given that the production server now has the files that were on development for Thai,
When I add the prod URL to the prod manifest and I select "ภาษาไทย" as a language,
Then I should see the app icon for FTM.

Given that I see the app icon for FTM,
When I open the app and play through the first level in its entirety,
Then I should see text in Thai and hear Thai audio.

**Comment by burrage** [comment]
Can someone check this [diacritic issue mentioned in the QA for level 62](https://docs.google.com/document/d/1y-PBWgwW4INgwPPh7kb-DrQM0OVBw888/edit?usp=sharing&ouid=106681327600299394280&rtpof=true&sd=true)?

Thank you!

**Comment by divyahariharan2103** [comment]
@burrage This is available for local QA

**Comment by burrage** [comment]
@Nikhil77sutara @divyahariharan2103 Sending this one back to devs as the diacritic issue that starts on level 62 is still present.

See [diacritic issue mentioned in the QA for level 62](https://docs.google.com/document/d/1y-PBWgwW4INgwPPh7kb-DrQM0OVBw888/edit?usp=sharing&ouid=106681327600299394280&rtpof=true&sd=true) again.

The issue here is that it looks like the diacritic and the letter are being treated as two separate characters when they should be combined!

Thai seems to be behaving differently than all of our other languages with accent marks... I'm almost wondering if we need to solve this in the levelgen by putting ( )s around the character and diacritic to combine them?

ex. (ชุ)บ,(ชุ)น,(ดุ)ม,(มุ)ง,(ชุ)น

Or any other thoughts or ideas?

**Comment by Nikhil77sutara** [comment]
Hey @burrage ,

We have gone through the docs and in the screenshots which is attached there we found out that the user didn't have the latest version of ftm which is 1.0.24 in that screenshot the version is older that's why it might not have the latest fixes!

<img width="960" alt="Screenshot 2024-01-08 184148" src="https://github.com/curiouslearning/FeedTheMonsterJS/assets/134049291/fdd032f9-9745-43d2-a0c9-431dc9dcb0ec">

**Comment by burrage** [comment]
@Nikhil77sutara That's correct, but it is still a problem on the latest version-- at least for me when I looked at it.

![Screenshot_2024-01-08-10-22-45-252_org curiouslearning containerdev](https://github.com/curiouslearning/FeedTheMonsterJS/assets/5167186/502132ef-91f1-485f-a27a-99634fe853f6)

Notice how the ","-like diacritic is its own stone? It shouldn't be. 

Updated my previous post to use the correct parentheses [ ] for combining if that is indeed the issue. I'm not sure why Thai would be like this and every other language that uses accent marks was not like this.

**Comment by Nikhil77sutara** [comment]
Hy @burrage ,
I have checked the json and I found out that there are three stone texts coming for a word of two letters.
 "targetstones": [
            {
              "StoneText": "ช"
            },
            {
              "StoneText": "ุ"
            },
            {
              "StoneText": "บ"
            }
          ],

**Comment by divyahariharan2103** [comment]
@burrage this is ready for the local QA to test !!

**Comment by burrage** [comment]
OK @Nikhil77sutara ! Using [ ]s in the levelgen worked wonders in combining the accent mark and the letter so we did that allll throughout the levelgen where we needed to do it.

Let's rebuild the JSON and push the latest version to the dev server! Thanks!

**Comment by Nikhil77sutara** [comment]
> OK @Nikhil77sutara ! Using [ ]s in the levelgen worked wonders in combining the accent mark and the letter so we did that allll throughout the levelgen where we needed to do it.
> 
> Let's rebuild the JSON and push the latest version to the dev server! Thanks!

Sure @burrage

**Comment by Ashish1998** [comment]
@burrage This is ready for local QA to check.
