### ISSUE TITLE
Launch "Tsonga" language to production

### ISSUE THREAD

**Issue by divyahariharan2103** [curiouslearning/FeedTheMonsterJS#759]
**Acceptance Criteria**
Given that the production server now has the files that were on development for Tsonga,
When I add the prod URL to the prod manifest and I select "Xitsonga" as a language,
Then I should see the app icon for FTM.

Given that I see the app icon for FTM,
When I open the app and play through the first level in its entirety,
Then I should see text in Tsonga and hear Tsonga audio.

**Comment by burrage** [comment]
Content group put audio in the wrong folder... Getting it to the right spot.

**Comment by amitsinghsutara** [comment]
Hey @burrage ,
For Tsonga we were able to find few missing audios on the github expect this one!
n'wina

**Comment by burrage** [comment]
@amitsinghsutara OK cool I just ran the script and just wanted to verify that you found these ones in bold?

**r.mp3** n'wina.mp3 **y.mp3** **v.mp3**

Do you want to throw those into the [Tsonga "Letters" folder](https://drive.google.com/drive/folders/1WTg8KtOHnRGu72YskNNVsdlASCSkeP94?usp=drive_link) so that when we run the script, those don't show up as missing?

Thanks Amit!

**Comment by amitsinghsutara** [comment]
Thanks @burrage  :raised_hands::raised_hands:

**Comment by divyahariharan2103** [comment]
Hi @burrage This is ready for Local QA to test !!

**Comment by burrage** [comment]
@divyahariharan2103 Since this has been in QA for ages and is now ready for prod launch, I'm leaving this unassigned at the moment. Anyone that wants to do a prod launch / has capacity can pick this up :-)
