### ISSUE TITLE
Lagging in drag and drop in low end device.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#838]
**Describe the bug**

- When we drag a stone the stone is not moving according to the finger movement.
- After giving the input sometimes the game will hang.
- The feedback animation will not complete or will not be properly displayed.

**Screen Record**
https://drive.google.com/file/d/16HK4DtgKVhmMd1oqZYpLJUEG1l4E5Nz4/view?usp=drive_link

**Smartphone (please complete the following information):**
 - Device: Lenovo TB-7305F
 - OS: Android 9
 - RAM 1GB

**Comment by divyahariharan2103** [comment]
@burrage Please let us know if we can pause the work on this task for now

**Comment by burrage** [comment]
Absolutely-- it is in the Backlog already :-)

**Comment by burrage** [comment]
What might be interesting to investigate here is to identify what exactly is happening to cause the lag. Is it because the draw method is being called so many times to follow a user's finger? Is it because it is redrawing both the stone + letter? Are there other methods that are less memory intensive that others may have found for dragging and object on screen in a web app?

**Comment by burrage** [comment]
Also we should split this card into smaller increments of effort starting with identifying root cause.

**Comment by divyahariharan2103** [comment]
Converting this task into epic and attaching a task for now that needs investigation
