### ISSUE TITLE
Optimization: Merging multiple sprite sequence into one image

### ISSUE THREAD

**Issue by divyahariharan2103** [curiouslearning/FeedTheMonsterJS#907]
We tried to merge different sprite sequence into one image so it can load into a single go.
			
Why we doing so?
			
whenever we start dragging answer animation needs to switch between idle to eating and it lags there while doing so because it has to load different images.

**Comment by ashishkrr** [comment]
As we tried to make all monster images into spritesheet for a particular phase of monster, we found issue that in low end device that image drawing is taking very long time, image size for the spritesheet is 900kb, and am not able to compress below 900kb.

I have tried offcanvas draw in worker thread, but that workers performs more better in high end device but low end device it's loading the build itself.

**Comment by ashishkrr** [comment]
![monster_01](https://github.com/curiouslearning/FeedTheMonsterJS/assets/35664866/777a0ba6-969b-4cec-af0c-933d6af1ed4f)
@burrage this is the spritesheet image we create, before it was 4mb, using tiny.png tool we made it to 900kb, but we need make it to very low as much as possible.

**Comment by divyahariharan2103** [comment]
@burrage please let us know if any update on this

**Comment by burrage** [comment]
@ashishkrr Sure, I can connect with Geoff to see if he has any ideas on optimizing the sprite sheet further.

**Comment by burrage** [comment]
@ashishkrr Is there a size we would aim for where the performance wouldn't drag as much?

**Comment by burrage** [comment]
Jeff's response:

"I was able to take it down to about 700KB using the following settings in Photoshop's "Save for Web..." feature:

![image (2)](https://github.com/curiouslearning/FeedTheMonsterJS/assets/5167186/668dc172-3e33-475c-ac1f-d84ebb678756)


The key is bumping it down to PNG-8 rather than PNG-24 and reducing the colors. The downside of this approach is that there's no gradients or gradient transparency. That's not so much an issue with the gradients (even stepped down to 32 colors, the dithering still looks pretty good at that scale), but the indexed transparency does not look good unless it's matted to the correct background color (I just guessed the blue – you would have to match it to the actual background color). 

I think also resizing it to power-of-two dimensions and packing it a little tighter might work to save some more file size, but not so much as using PNG-8.

Here's a good primer on it: https://www.smashingmagazine.com/2009/07/clever-png-optimization-techniques/

It's a little old, but PNG has been around for a long time, so it's still relevant info for optimizing PNG's.

Hope this helps!"

**Comment by burrage** [comment]
@ashishkrr It seems to go lower (by more) we would need to ditch the shadow effect on the character and replace it with a non-gradient shadow which may be problematic as the background will change over time... so I'm not sure how I'd feel about doing that to save ~200KB.

Maybe going back to the question earlier about what our target size should be-- what's acting as the bottleneck here on a device for rendering the spritesheet? Is it the amount of RAM? The CPU? Both?

Perhaps this is actually a good point to start drawing a line in the sand about what our minimum device requirements are. We should be doing that anyway as we cannot optimize forever without the quality of presentation starting to take a hit.

**Comment by ashishkrr** [comment]
@burrage The problem in performance during drag comes because of change in image we are doing (whenever we are changing animation ex:- idle to drag, drag to eat), so to avoid these we tried to merge all different animation spritesheet into single spritesheet, so image will be same we need just need to adjust the co-ordinates to draw and perform animation.

After merging all the spritesheet of (idle, eat, drag, split) into single spritesheet image size became 900kb and that is taking time to draw in low end devices,

if this is optimized upto 200kb, am hoping that will work fine, and about color or some gradient need to adjust, i will do it programmatically.
please share the png file, will test and see.

**Comment by burrage** [comment]
@ashishkrr Sure, just asked Geoff Beatty for that ~700KB spritesheet but unsure if he is on break yet or not. We can put a pin in this until the new year.

**Comment by burrage** [comment]
![lightning-egg-sprite-sheet-example-PNG8](https://github.com/curiouslearning/FeedTheMonsterJS/assets/5167186/d77a10b0-3285-46a6-be04-a03e1a4e35d5)

Attaching that ~700KB spritesheet with the solid color, non-gradient shadow for you to play around with @ashishkrr !

**Comment by burrage** [comment]
@ashishkrr To finish out this task card and consider it "Done" since I don't think we can really optimize the spritesheet significantly beyond what we've done... would you mind also writing out any minimum device specifications we might recommend? We mentioned a device with at least 2GB RAM which is a perfect start but is there anything else that would contribute that we might want to include in our "minimum device specifications" that we would recommend to an end-user?

Thanks!

**Comment by Ashish1998** [comment]
The minimum requirements (Specifications) for running the application are,
RAM - 2GB
OS - Android 9
