### ISSUE TITLE
Additional key-value pairs being reported into session_start FTM Firebase event

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#971]
**Describe the bug**
In querying BigQuery for [session_start events](https://docs.google.com/document/d/1HJ8GG5w6gDqHrgs7YW0FRHhQAMYPVVrG7M81vokcjVY/edit#heading=h.w21k2p437v0z), we are being returned key-value pairs that are associated with other event types.

<img width="989" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2dSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f798e6b43c9236121ad88fb74521e806c4eb61a/Screenshot%202024-01-30%20at%201.27.02%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 1.27.02 PM.png" />

<img width="958" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK29SQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8ab0a5c270ceeef88bd87374aa983b5917b22bf/Screenshot%202024-01-30%20at%201.27.23%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 1.27.23 PM.png" />

**To Reproduce**

See queries in screenshots to run in BigQuery and view the results.

**Expected behavior**
All event types should only have the key-value listed in the spec sheet.

**Screenshots**
See above.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
We should probably do a re-QA on [all FTM event types outlined in the spec](https://docs.google.com/document/d/1HJ8GG5w6gDqHrgs7YW0FRHhQAMYPVVrG7M81vokcjVY/edit?usp=sharing) as something has changed since the last time we QA'd these.

**Comment by Nikhil77sutara** [comment]
Hi @burrage ,
I hope you are doing good. I wanted to provide you with an update on our ongoing efforts to resolve the issue we've encountered with the ftm_language parameter in the analytics event data.
Both Ashish Kumar and I are actively engaged in investigating the root cause of this issue. In our exploration, we referred to the documentation ( https://docs.google.com/spreadsheets/d/1tE4a0TcJZj-q14_5Xv96aR4z_dnEA2HZG8KLxcl-p8g/edit#gid=1321183123) specifically related to the start_session event parameters. It was reassuring to note that we are not utilizing any additional parameters such as target or success_or_failure within this context.
As part of our investigation, we are also exploring ways to streamline the analytics event data by removing unnecessary parameters. We understand the importance of optimizing the data for accuracy and efficiency.
If you have any insights, ideas, or tips that you believe might be beneficial in this context, we would greatly appreciate your input.
Rest assured, I'll keep you updated on our progress, providing insights into potential solutions as we continue this debugging process.

**Comment by Nikhil77sutara** [comment]
Hi @burrage ,

Hope you are doing good. We've optimized the session_start event in Firebase by eliminating unnecessary parameters and introducing event dates with timestamps. These modifications are live in the development APK . Please take a moment to review the corresponding data changes in BigQuery for the dev APK , also am sharing some screenshots for dev apk data. Once we merge these updates into the production environment, the improvements will seamlessly reflect there as well. If you have any queries or need more details, please let me know.
<img width="960" alt="Screenshot 2024-02-19 143127" src="https://github.com/curiouslearning/FeedTheMonsterJS/assets/134049291/2ae54666-ab3f-4f93-a0bb-ca054a9e196c">
<img width="960" alt="Screenshot 2024-02-19 143258" src="https://github.com/curiouslearning/FeedTheMonsterJS/assets/134049291/4d4ae7be-47b8-4b28-b698-b2f06dae1315">
<img width="960" alt="Screenshot 2024-02-19 143316" src="https://github.com/curiouslearning/FeedTheMonsterJS/assets/134049291/58b7bf06-2f0f-4ea8-aa60-09cd7ba1c49c">
